name: donation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.1.2
  layout: ^1.0.5
  parse_server_sdk_flutter: 
    git: 
      url: https://github.com/Marcone-zz/parse-sdk-flutter
      path: packages/flutter
      ref: master
  result_dart: ^2.1.0
  signals: ^6.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700